### ISSUE TITLE
Show Tags

### ISSUE THREAD

**Issue by bjrne** [HPI-SWA-Teaching/SWT17-Project-01#12]
**As a** developer
**I want to** see tags in the tree view
**In order to** see all versions.

**Comment by Blubl** [comment]
Is squot supporting tags? @j4yk

**Comment by j4yk** [comment]
Squot does currently not, though FileSystem-Git (the layer below) should. Though, the only reason that tags are missing in Squot is "was not necessary yet"...

Git has two kinds of tags: such with an own message, tagger etc. (proper tag objects in the repository) and such without ("lightweight tags"). The latter are references in .git/refs/tags/... which are just never moved. You can access these already with something similar to the code in `SquitRepository>>remoteHistorians`. You can also look at the class comments of `GitTag` and `GitLightweightTag` if you are interested.
