### ISSUE TITLE
Should we keep track of metrics like code coverage and how?

### ISSUE THREAD

**Issue by feeds** [HPI-SWA-Teaching/SWT17-Project-01#14]
Those would be useful for the presentation, as well as team reflection.
What could be covered:
- code coverage
- estimated vs. actual time of story, time per week

**Comment by bjrne** [comment]
I think we should, there are numerous services that integrate with github and/or travis. We just have to find one that is configurable for smalltalk :)

Time management will probably be more difficult. I use toggl.com for tracking my time spent on projects.

**Comment by Baschdl** [comment]
Code coverage is possible with coveralls over hpi-swa/smalltalkCI [(https://github.com/hpi-swa/smalltalkCI#coverage-testing)](https://github.com/hpi-swa/smalltalkCI#coverage-testing)

**Comment by Baschdl** [comment]
Coveralls is setup for this repository. @HPI-SWA-Teaching/2017-student-team-01 Do we need more? Otherwise we can close this issue.

**Comment by Baschdl** [comment]
@HPI-SWA-Teaching/2017-student-team-01 😢

**Comment by bjrne** [comment]
Close it in 4...

**Comment by feeds** [comment]
I'll do the Paper feedback thing and bring it in next time :)

**Comment by Baschdl** [comment]
But somehow coveralls doesn't work yet

**Comment by bjrne** [comment]
@Baschdl I'll look into that.

**Comment by Baschdl** [comment]
After fixing coveralls and no other comments I will close this issue now
