### ISSUE TITLE
Setup appveyor

### ISSUE THREAD

**Issue by bjrne** [HPI-SWA-Teaching/SWT17-Project-01#16]
Appveyor is an alternative to travis which can build on windows.

- [ ] Add appveyor yaml to repository

**Comment by Baschdl** [comment]
[https://ci.appveyor.com/project/Baschdl/swt17-project-01](https://ci.appveyor.com/project/Baschdl/swt17-project-01)

**Comment by Baschdl** [comment]
@fniephaus We need again admin rights to setup appveyor and pull request settings

**Comment by fniephaus** [comment]
Temporarily granted.
Please re-assign when done...

**Comment by Baschdl** [comment]
@fniephaus Done and revoked admin rights.

**Comment by fniephaus** [comment]
Thanks!

**Comment by Baschdl** [comment]
Fixed with #22
