### ISSUE TITLE
US-01: Squot API for fetching Commits

### ISSUE THREAD

**Issue by Blubl** [HPI-SWA-Teaching/SWT17-Project-01#19]

**Comment by Baschdl** [comment]
When you explore the LazyListMorph in the left upper corner of Squot [1] you find in the list ```listItems``` a object ```loadedHistorian```. This historian contains a SquitRepository with a ```versionsCache``` full of our commits (SquitVersion). The corresponding class is ```SquitRepository``` in the package ```Squit-Core```.
Also, you can load all available Historians (branches) via `repository historians`



[1]
![projects](https://cloud.githubusercontent.com/assets/3034832/26059529/5dc93d56-3982-11e7-91a0-3066f25d0223.png)

**Comment by Baschdl** [comment]
When we receive a repository we are able to get all commits/SquitVersions with ```versionsCache keys```. On each version we can call ```commit```, ```message``` and ```metadata``` (information from ```metadata``` follows):
``` Squeak
#author. commit author name.
		#authorEmail. commit author email.
		#email. commit author email.
		#authoringTimeStamp. commit author timeStamp.
		#timestamp. commit author timeStamp.
		#committer. commit committer name.
		#committerEmail. commit committer email.
		#commitTimeStamp. commit committer timeStamp.
		#message. commit message.
		#hash. commit hexHash
```

Sadly no sign of a signed commit. [Here it would be great to have each US as an issue in order to reference this issue] @Lariiii Did you miss the signed commit US in the wiki?

@Blubl @feeds @bjrne @Lariiii Where do we get the repository? With a text field for the git link + cloning? Or do we use one from the Squit browser for the first prototype?

**Comment by feeds** [comment]
Our tool should have something like a drop-down list for the repo selection, maybe add that to the tasks of #19?

**Comment by feeds** [comment]
(I remember the customer saying something about a stand-alone tool)

**Comment by Baschdl** [comment]
@feeds But I don't think a drop-down list is necessary for the first prototype. I would add a new task for this and assign the task to an other user story.

**Comment by feeds** [comment]
So we would hardcode this?

**Comment by Baschdl** [comment]
Yes, I would say it's appropriate for the first prototype

**Comment by Baschdl** [comment]
As discussed with @bjrne we could maybe use self-update for our project (if we don't integrate our view in Squot directly).
Furthermore this method is a example for the creation of a repository/working copy etc. (everything above ```SquotWorkingCopy registered```).

SquitBrowser >> selfUpdate
``` Squeak
selfUpdate
	"UpdateWorkingCopy := nil"
	UpdateWorkingCopy ifNil: [
		UpdateWorkingCopy := SquotWorkingCopy new.
		UpdateWorkingCopy store: SquotImageStore new.
		UpdateWorkingCopy repository: (
			SquitRepository onDirectory: FileSystem memory / 'Squot').
		UpdateWorkingCopy repository gitRepository
			addRemote: 'origin' url: self selfUpdateRepository].
	SquotWorkingCopy registered
		detect: [:each | each name includesSubstring: 'Squot' caseSensitive: false]
		"This is likely to be a Squot developer, so interactively load current version"
		ifFound: [:selfWorkingCopy | self selfUpdateWithSquot: selfWorkingCopy]
		ifNone: [
			"Close all instances before updating to avoid any UI glitches"
			SquitBrowser allInstances do: [:each | each changed: #close].
			self selfUpdateFromMetacello.
			"UpdateWorkingCopy loadVersion: UpdateWorkingCopy baseVersion interactive: false."
			SquitBrowser open].
```

**Comment by feeds** [comment]
.
