### ISSUE TITLE
Repo admin for webhooks

### ISSUE THREAD

**Issue by Baschdl** [HPI-SWA-Teaching/SWT17-Project-01#2]
We need admin access on this repo to set up a webhook for Waffle.io

- [x] Write mail

**Comment by feeds** [comment]
@feeds wants to do this :)

**Comment by feeds** [comment]
@feeds sorr< for the spam

**Comment by fniephaus** [comment]
Admin permissions granted.
Please set up your webhooks and re-assign the issue to me as soon as you are done.

**Comment by bjrne** [comment]
Done setting up waffle.io. We may need this again in the future for travis or continuous integration.

**Comment by fniephaus** [comment]
Thanks. I have revoked the permissions, as we can only grant them temporarily.
Please note that Travis is already set up for the repository.
But feel free to get in touch with us if you need admin permissions again.
