### ISSUE TITLE
Algorithm for graph visualisation

### ISSUE THREAD

**Issue by Baschdl** [HPI-SWA-Teaching/SWT17-Project-01#25]
We need a algorithm to place pretty edges and vertices.

Some inspirations:
- Simple bash script: [https://github.com/albfan/git-graph](https://github.com/albfan/git-graph)
- Nice graphics, didn't find algorithm/code: [http://bit-booster.com/graph.html](http://bit-booster.com/graph.html)
- Javascript, bigger project: [https://github.com/nicoespeon/gitgraph.js](https://github.com/nicoespeon/gitgraph.js)
- ASCII Graph: [https://bitbucket.org/mirror/mercurial-stable/src/9606edb8777e/hgext/graphlog.py?fileviewer=file-view-default](https://bitbucket.org/mirror/mercurial-stable/src/9606edb8777e/hgext/graphlog.py?fileviewer=file-view-default)
- Complex visualisation: [https://github.com/git-up/GitUp](https://github.com/git-up/GitUp)

**Comment by Baschdl** [comment]
@feeds I guess you are doing this after creating a branch for this purpose. Could you please assign yourself?

**Comment by feeds** [comment]
```
    ___
   /     @bjrne - icons
--<                                                     >--- 🥅 (Who will make it?)
   \___  @feeds - morphic
```

**Comment by bjrne** [comment]
Can still use some improvements but is done in the scope of this issue
