### ISSUE TITLE
Formulation user stories

### ISSUE THREAD

**Issue by Baschdl** [HPI-SWA-Teaching/SWT17-Project-01#35]
@HPI-SWA-Teaching/2017-student-team-01 Do we want to write all our user stories in the "**As a** ... **I would like to** ... **in order to**" form?

**Comment by bjrne** [comment]
Is there a need for another form? I like it because it captures the user, the aim and the intention.

**Comment by feeds** [comment]
I like it very much as it is

**Comment by bjrne** [comment]
Will be closed after reaction of @Lariiii and @Blubl

**Comment by Lariiii** [comment]
I approve it, too.

**Comment by Baschdl** [comment]
@bjrne "Is there a need for another form?" No, but they aren't in this form

**Comment by Baschdl** [comment]
They aren't in this form on the wiki [wiki/User-Stories](https://github.com/HPI-SWA-Teaching/SWT17-Project-01/wiki/User-Stories)

**Comment by Baschdl** [comment]
@Lariiii Do you want to do this (after digitalising our cards)? (I already formulated some on the closed issues)

**Comment by Lariiii** [comment]
Yes, I will do that.

**Comment by Lariiii** [comment]
I am not sure what the correct user story formulation for "7. Show difference between selected commit and ancestor" is. Any ideas?

**Comment by Baschdl** [comment]
Something like that [https://github.com/HPI-SWA-Teaching/SWT17-Project-01/pull/29/commits/497840a82a291a59bd8b7a496fb3ec8c16cd4a92](https://github.com/HPI-SWA-Teaching/SWT17-Project-01/pull/29/commits/497840a82a291a59bd8b7a496fb3ec8c16cd4a92)
