### ISSUE TITLE
Revive the variable names in GanaSquitVersionWrapper

### ISSUE THREAD

**Issue by Lariiii** [HPI-SWA-Teaching/SWT17-Project-01#39]
Give the variables t1, t2, ..., tn better names.

**Comment by Lariiii** [comment]
I renamed the variables in 'summary' and in 'historian'. @feeds could you rename the remaining variables? There is a new branch 'variable-renaming'.

**Comment by Baschdl** [comment]
@feeds Did you merge the branch `variable-renaming`?

**Comment by feeds** [comment]
no, i just fixed the stuff on transcrpt output...

**Comment by feeds** [comment]
i did not expect someone to opem a branch for such a minor change. Its all done now, so ill delete the other branch

**Comment by feeds** [comment]
also it seems @Lariiii did not push her branch... or she did it on the one commit happend on transcr-output.

Anyways, its done
