### ISSUE TITLE
US-2: Construct a Test-repo 

### ISSUE THREAD

**Issue by feeds** [HPI-SWA-Teaching/SWT17-Project-01#42]

**Comment by feeds** [comment]
@HPI-SWA-Teaching/2017-student-team-01 I added a few mock objects to make it easier to generate a testable commit history. Please have a look at the `VersionListBuilderTest` if you want to understand the workings.

Also, please feel free to add some tests! (We only have 3️⃣ now)

**Comment by Baschdl** [comment]
#68 adds some more test repos
