### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by bjrne** [HPI-SWA-Teaching/SWT17-Project-01#72]
## Categories: @Baschdl
- [x] GanaTreeItemWrapper
- [ ] GanaVersionListBuilder (depends on refactoring of visitListItem)
- [x] GanaVersionWrapper

## Class Comments: @bjrne
- [x] GanaTreeItemWrapper
- [x] GanaVersionListBuilder
- [x] GanaVersionWrapper

## Refactoring Flags:

- [ ] GanaBrowser>commitList
- [x] GanaTreeItemWrapper>asString (move magic numbers into class side dict)
- [x] GanaTreeItemWrapper>historianString
- [ ] GanaVersionListBuilder>initializeSearchFrontierFrom:
- [ ] GanaVersionListBuilder>visitListItem:

## Further refactoring potential:
- [ ] ~~Dualism between `asString` and `summary`~~ Closed as unimportant bj Bjarne

# Feedback from Tom
## GanaPerformanceTest>>testBigRepo
- [x] Time millisecondsToRun: [] vs [] timeToRun
- [x] konstante in eine funktion schieben?
- [x] self isFastEnough: [ganaBrowser searchTerm: ...] (das macht dann das assert: etc)

## GanaBranchGraph
- [x] könnte der auch von Morph inheriten statt einen graph zu haben? andernfalls vielleicht in graphbuilder umbennen? - Finde ich gut, glaube es spricht nichts dagegen (Bjarne)
- [x] self cellSize / 2 asPoint (asPoint braucht ihr nicht) @bjrne
- [x] middle := kann bei dem ifTrue:ifFalse: rausgezogen werden `middle := boolean ifTrue: [1] ifFalse: [2]`
Anmerkung: reine stilfrage würde ich sagen, unwichtig (- Bjarne)
- [x] formatierungsvorschlag, falls der mit euren style guides kompatibel ist: @bjrne
	statt:
```
self verticalSuccessorDict at: youngestChild ifPresent: [:temp | self position: commit inNewColumnForRow: row] "new branch"
												ifAbsentPut: [self putCommit: commit at: ((self positionDict at: youngestChild) x @row)]
```
das hier:
```
self verticalSuccessorDict
		at: youngestChild
		ifPresent: [:temp | self position: commit inNewColumnForRow: row] "new branch"
		ifAbsentPut: [self putCommit: commit at: ((self positionDict at: youngestChild) x @row)]
```

## GanaBrowser
- [x] `#applyAuthorFilter:on:,#applyMessageFilter:on: includesSubstring:` vs `includesSubstring:caseSensitive:`
- [x] #hasSearchTerm self searchTerm notEmpty

# Linter

- [ ] make searchterm different

**Comment by Baschdl** [comment]
Done 👍
